replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 8085
  targetPort: 8085
  nodePort: 30080

ingress:
  enabled: false

resources: {}

autoscaling:
  enabled: false

